name: Python Package using Conda
channels:
  - defaults
  - conda-forge
  - bioconda  # Additional channel if needed
dependencies:
  - python=3.10
  - flake8
  - pytest
  - numpy=1.21
  - pandas=1.3.3
  - scikit-learn
  - matplotlib
  # Add other dependencies as needed
  - pip:
      - some-pip-only-package
